// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0CJ9uwXnfl315NkdyOpiUu5xMgLVt8YM',
    appId: '1:172297260942:web:d36de6a4f52899c12d1edf',
    messagingSenderId: '172297260942',
    projectId: 'tudo-em-casa-receita',
    authDomain: 'tudo-em-casa-receita.firebaseapp.com',
    storageBucket: 'tudo-em-casa-receita.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXoRFSQRtczRaAqZ9h76tLp6NEPT5A_po',
    appId: '1:172297260942:android:6ccc5c8ff33a07eb2d1edf',
    messagingSenderId: '172297260942',
    projectId: 'tudo-em-casa-receita',
    storageBucket: 'tudo-em-casa-receita.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUEfOhVmWMG-fZ3I2hTcFKhSJys3zLQRA',
    appId: '1:172297260942:ios:84f0e57a1117512c2d1edf',
    messagingSenderId: '172297260942',
    projectId: 'tudo-em-casa-receita',
    storageBucket: 'tudo-em-casa-receita.appspot.com',
    iosClientId: '172297260942-ai9pkvn6si1j2bj3a67reuk6q41mods1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tudoEmCasaReceitas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUEfOhVmWMG-fZ3I2hTcFKhSJys3zLQRA',
    appId: '1:172297260942:ios:84f0e57a1117512c2d1edf',
    messagingSenderId: '172297260942',
    projectId: 'tudo-em-casa-receita',
    storageBucket: 'tudo-em-casa-receita.appspot.com',
    iosClientId: '172297260942-ai9pkvn6si1j2bj3a67reuk6q41mods1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tudoEmCasaReceitas',
  );
}
